- name: zsh | Set zsh as the default shell
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
- name: Clone dotfiles repo from GitHub
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_root }}"
    clone: yes
    force: yes
- name: zsh | Download plugins
  git:
    repo: "{{ item.url }}"
    dest: "{{ dotfiles.zsh.path }}/{{ item.name }}"
    clone: yes
    force: yes
  with_items: "{{ zsh_plugins }}"
- name: Clone base16-shell repo
  git:
    repo: "https://github.com/chriskempson/base16-shell.git"
    dest: "{{ config_root }}/base16-shell"
    clone: yes
    force: yes
- name: zsh | Create symbolic links
  file:
    path: "{{ dotfiles.zsh.link_dir }}/{{ item }}"
    state: link
    src: "{{ dotfiles.zsh.path }}/{{ item }}"
    force: yes
  with_items: "{{ dotfiles.zsh.link_items }}"
- name: neovim | Detect dein installation
  command: test -d "{{ ansible_env.HOME }}/.config/nvim/bundle"
  register: dein_already_installed
  failed_when: dein_already_installed.stderr != ""
- name: neovim | Download dein installer if needed
  get_url:
    url: "https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh"
    dest: "{{ ansible_env.HOME }}/dein_installer.sh"
  when: dein_already_installed.rc == 1 # run only when not installed
- name: neovim | Run dein installer if needed
  command: bash "{{ ansible_env.HOME }}/dein_installer.sh" "{{ ansible_env.HOME }}/.config/nvim/bundle"
  when: dein_already_installed.rc == 1 # run only when not installed
- name: neovim | Create symbolic links
  file:
    path: "{{ dotfiles.nvim.link_dir }}/{{ item }}"
    state: link
    src: "{{ dotfiles.nvim.path }}/{{ item }}"
    force: yes
  with_items: "{{ dotfiles.nvim.link_items }}"
