config_root: "{{ ansible_env.HOME }}/.config"
zsh_dotfiles_root: "{{ ansible_env.HOME }}/.dotfiles/zsh"
zsh_plugins:
  - { name: colored-man-pages_mod, url: "https://github.com/zuxfoucault/colored-man-pages_mod.git" }
  - { name: zsh-completions, url: "https://github.com/zsh-users/zsh-completions.git" }
  - { name: zsh-syntax-highlighting, url: "https://github.com/zsh-users/zsh-syntax-highlighting.git" }
