- name: Install Pip
  become: yes
  package:
    name: python-pip
    state: present

- name: Install Python packages
  pip:
    name: "{{ item }}"
    state: present
    extra_args: "--user"
    executable: "{{ which_pip }}"
  with_items: "{{ python_packages }}"
