- name: install system packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    autoclean: yes
    autoremove: yes
  with_items: "{{ packages.system }}"
# - name: install python packages
#   pip:
#     name: "{{ item }}"
#     state: latest
#     extra_args: --user
#   with_items: "{{ packages.python }}"
# - name: create user directories
#   file:
#     path: "{{ item }}"
#     state: directory
#   with_items: "{{ dirs }}"
# - debug:
#     var: ansible_env
- name: Create install script directory
  file:
    path: "{{ ansible_env.HOME }}/installers"
    state: directory
- name: Check Rust installation
  stat:
    path: "{{ ansible_env.HOME }}/.cargo/bin/rustup"
  register: rust_stat_result
- name: Download Rust installer
  get_url:
    url: "https://sh.rustup.rs"
    dest: "{{ ansible_env.HOME }}/installers/rustup_init.sh"
  when: rust_stat_result.stat.exists == False
- name: Run Rust installer
  command: "sh {{ ansible_env.HOME }}/installers/rustup_init.sh --default-toolchain nightly"
  when: rust_stat_result.stat.exists == False
- name: Remove Rust installer
  file:
    path: "{{ ansible_env.HOME }}/installers/rustup_init.sh"
    state: absent
- name: Install Rust packages
  shell: "/home/zmitchell/.cargo/bin/cargo install {{ item }}"
  with_items: "{{ packages.rust }}"
  # Will throw an error if already installed
  ignore_errors: yes
