- name: Ensure that neovim is installed
  become: yes
  apt:
    name: neovim
    state: latest

- name: Ensure that neovim Python package is installed
  pip:
    name: neovim
    state: latest
    executable: /usr/bin/pip3
    extra_args: --user

- name: Detect dein installation
  command: test -d "{{ ansible_env.HOME }}/.config/nvim/bundle"
  register: dein_already_installed
  failed_when: dein_already_installed.stderr != ""

- name: Download dein installer
  get_url:
    url: "https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh"
    dest: "/tmp/dein_installer.sh"
  when: dein_already_installed.rc == 1

- name: Run dein installer
  command: bash /tmp/dein_installer.sh "{{ neovim_config_root }}/bundle"
  when: dein_already_installed.rc == 1

- name: Remove dein installer
  file:
    path: /tmp/dein_installer.sh
    state: absent

- name: Copy init.vim
  copy:
    src: init.vim
    dest: "{{ neovim_config_root }}/init.vim"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
